-- begin ACCUMED_PROVIDER
alter table ACCUMED_PROVIDER add constraint FK_ACCUMED_PROVIDER_PRIMARY_SPECIALTY_ID foreign key (PRIMARY_SPECIALTY_ID) references ACCUMED_SPECIALITY(ID)^
create index IDX_ACCUMED_PROVIDER_PRIMARY_SPECIALTY on ACCUMED_PROVIDER (PRIMARY_SPECIALTY_ID)^
-- end ACCUMED_PROVIDER
-- begin ACCUMED_SPECIALITY
create unique index IDX_ACCUMED_SPECIALITY_UNIQ_SPECIALTY_CODE on ACCUMED_SPECIALITY (SPECIALTY_CODE) where DELETE_TS is null ^
-- end ACCUMED_SPECIALITY
-- begin ACCUMED_MINISTRY_OF_HEALTH_OFFICE
create unique index IDX_ACCUMED_MINISTRY_OF_HEALTH_OFFICE_UNIQ_OFFICE_CODE on ACCUMED_MINISTRY_OF_HEALTH_OFFICE (OFFICE_CODE) where DELETE_TS is null ^
-- end ACCUMED_MINISTRY_OF_HEALTH_OFFICE
-- begin ACCUMED_PATIENT_ADMISSION
alter table ACCUMED_PATIENT_ADMISSION add constraint FK_ACCUMED_PATIENT_ADMISSION_FACILITY_ID foreign key (FACILITY_ID) references ACCUMED_FACILITY(ID)^
alter table ACCUMED_PATIENT_ADMISSION add constraint FK_ACCUMED_PATIENT_ADMISSION_PATIENT_ID foreign key (PATIENT_ID) references ACCUMED_PATIENT(ID)^
create index IDX_ACCUMED_PATIENT_ADMISSION_FACILITY on ACCUMED_PATIENT_ADMISSION (FACILITY_ID)^
create index IDX_ACCUMED_PATIENT_ADMISSION_PATIENT on ACCUMED_PATIENT_ADMISSION (PATIENT_ID)^
-- end ACCUMED_PATIENT_ADMISSION
-- begin ACCUMED_PATIENT
alter table ACCUMED_PATIENT add constraint FK_ACCUMED_PATIENT_FAMILY_DOCTOR_ID foreign key (FAMILY_DOCTOR_ID) references ACCUMED_PROVIDER(ID)^
create index IDX_ACCUMED_PATIENT_FAMILY_DOCTOR on ACCUMED_PATIENT (FAMILY_DOCTOR_ID)^
-- end ACCUMED_PATIENT

-- begin ACCUMED_CLAIM
alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_PATIENT_ID foreign key (PATIENT_ID) references ACCUMED_PATIENT(ID)^
alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_REFERRED_BY_ID foreign key (REFERRED_BY_ID) references ACCUMED_PROVIDER(ID)^
alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_PROVIDER_ID foreign key (PROVIDER_ID) references ACCUMED_PROVIDER(ID)^
alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_FACILITY_ID foreign key (FACILITY_ID) references ACCUMED_FACILITY(ID)^
create index IDX_ACCUMED_CLAIM_REFERRED_BY on ACCUMED_CLAIM (REFERRED_BY_ID)^
create index IDX_ACCUMED_CLAIM_FACILITY on ACCUMED_CLAIM (FACILITY_ID)^
create index IDX_ACCUMED_CLAIM_PATIENT on ACCUMED_CLAIM (PATIENT_ID)^
create index IDX_ACCUMED_CLAIM_PROVIDER on ACCUMED_CLAIM (PROVIDER_ID)^
-- end ACCUMED_CLAIM
-- begin ACCUMED_CLAIM_LINE
alter table ACCUMED_CLAIM_LINE add constraint FK_ACCUMED_CLAIM_LINE_CLAIM_ID foreign key (CLAIM_ID) references ACCUMED_CLAIM(ID)^
alter table ACCUMED_CLAIM_LINE add constraint FK_ACCUMED_CLAIM_LINE_SERVICE_CODE_ID foreign key (SERVICE_CODE_ID) references ACCUMED_BILLABLE_SERVICE_CODE(ID)^
create index IDX_ACCUMED_CLAIM_LINE_CLAIM on ACCUMED_CLAIM_LINE (CLAIM_ID)^
create index IDX_ACCUMED_CLAIM_LINE_SERVICE_CODE on ACCUMED_CLAIM_LINE (SERVICE_CODE_ID)^
-- end ACCUMED_CLAIM_LINE
-- begin ACCUMED_SERVICE_CODE
create unique index IDX_ACCUMED_SERVICE_CODE_UNIQ_SERVICE_CODE on ACCUMED_SERVICE_CODE (SERVICE_CODE) where DELETE_TS is null ^
-- end ACCUMED_SERVICE_CODE
-- begin ACCUMED_SERVICE_CODE_RULE
alter table ACCUMED_SERVICE_CODE_RULE add constraint FK_ACCUMED_SERVICE_CODE_RULE_SERVICE_CODE_ID foreign key (SERVICE_CODE_ID) references ACCUMED_SERVICE_CODE(ID)^
create index IDX_ACCUMED_SERVICE_CODE_RULE_SERVICE_CODE on ACCUMED_SERVICE_CODE_RULE (SERVICE_CODE_ID)^
-- end ACCUMED_SERVICE_CODE_RULE
-- begin ACCUMED_BILLABLE_SERVICE_CODE
alter table ACCUMED_BILLABLE_SERVICE_CODE add constraint FK_ACCUMED_BILLABLE_SERVICE_CODE_SERVICE_CODE_ID foreign key (SERVICE_CODE_ID) references ACCUMED_SERVICE_CODE(ID)^
create unique index IDX_ACCUMED_BILLABLE_SERVICE_CODE_UNIQ_BILLABLE_CODE on ACCUMED_BILLABLE_SERVICE_CODE (BILLABLE_CODE) where DELETE_TS is null ^
create index IDX_ACCUMED_BILLABLE_SERVICE_CODE_SERVICE_CODE on ACCUMED_BILLABLE_SERVICE_CODE (SERVICE_CODE_ID)^
-- end ACCUMED_BILLABLE_SERVICE_CODE
-- begin ACCUMED_QUICK_SERVICE_CODE_BILLABLE_SERVICE_CODE_LINK
alter table ACCUMED_QUICK_SERVICE_CODE_BILLABLE_SERVICE_CODE_LINK add constraint FK_AQSCBSCL_QUICK_SERVICE_CODE foreign key (QUICK_SERVICE_CODE_ID) references ACCUMED_QUICK_SERVICE_CODE(ID)^
alter table ACCUMED_QUICK_SERVICE_CODE_BILLABLE_SERVICE_CODE_LINK add constraint FK_AQSCBSCL_BILLABLE_SERVICE_CODE foreign key (BILLABLE_SERVICE_CODE_ID) references ACCUMED_BILLABLE_SERVICE_CODE(ID)^
-- end ACCUMED_QUICK_SERVICE_CODE_BILLABLE_SERVICE_CODE_LINK
-- begin ACCUMED_QUICK_SERVICE_CODE
create unique index IDX_ACCUMED_QUICK_SERVICE_CODE_UNIQ_QUICK_CODE on ACCUMED_QUICK_SERVICE_CODE (QUICK_CODE) where DELETE_TS is null ^
-- end ACCUMED_QUICK_SERVICE_CODE
