-- begin ACCUMED_PROVIDER
alter table ACCUMED_PROVIDER add constraint FK_ACCUMED_PROVIDER_PRIMARY_SPECIALTY_ID foreign key (PRIMARY_SPECIALTY_ID) references ACCUMED_SPECIALITY(ID)^
alter table ACCUMED_PROVIDER add constraint FK_ACCUMED_PROVIDER_MINISTRY_OF_HEALTH_OFFICE_ID foreign key (MINISTRY_OF_HEALTH_OFFICE_ID) references ACCUMED_MINISTRY_OF_HEALTH_OFFICE(ID)^
create index IDX_ACCUMED_PROVIDER_PRIMARY_SPECIALTY on ACCUMED_PROVIDER (PRIMARY_SPECIALTY_ID)^
create index IDX_ACCUMED_PROVIDER_MINISTRY_OF_HEALTH_OFFICE on ACCUMED_PROVIDER (MINISTRY_OF_HEALTH_OFFICE_ID)^
-- end ACCUMED_PROVIDER
-- begin ACCUMED_SPECIALITY
create unique index IDX_ACCUMED_SPECIALITY_UNIQ_SPECIALTY_CODE on ACCUMED_SPECIALITY (SPECIALTY_CODE) where DELETE_TS is null ^
-- end ACCUMED_SPECIALITY
-- begin ACCUMED_MINISTRY_OF_HEALTH_OFFICE
create unique index IDX_ACCUMED_MINISTRY_OF_HEALTH_OFFICE_UNIQ_OFFICE_CODE on ACCUMED_MINISTRY_OF_HEALTH_OFFICE (OFFICE_CODE) where DELETE_TS is null ^
-- end ACCUMED_MINISTRY_OF_HEALTH_OFFICE
-- begin ACCUMED_PATIENT_ADMISSION
alter table ACCUMED_PATIENT_ADMISSION add constraint FK_ACCUMED_PATIENT_ADMISSION_FACILITY_ID foreign key (FACILITY_ID) references ACCUMED_FACILITY(ID)^
alter table ACCUMED_PATIENT_ADMISSION add constraint FK_ACCUMED_PATIENT_ADMISSION_PATIENT_ID foreign key (PATIENT_ID) references ACCUMED_PATIENT(ID)^
create index IDX_ACCUMED_PATIENT_ADMISSION_FACILITY on ACCUMED_PATIENT_ADMISSION (FACILITY_ID)^
create index IDX_ACCUMED_PATIENT_ADMISSION_PATIENT on ACCUMED_PATIENT_ADMISSION (PATIENT_ID)^
-- end ACCUMED_PATIENT_ADMISSION
-- begin ACCUMED_PATIENT
alter table ACCUMED_PATIENT add constraint FK_ACCUMED_PATIENT_FAM_DOC_ID foreign key (FAM_DOC_ID) references ACCUMED_PROVIDER(ID)^
create index IDX_ACCUMED_PATIENT_FAM_DOC on ACCUMED_PATIENT (FAM_DOC_ID)^
-- end ACCUMED_PATIENT
