alter table ACCUMED_CLAIM_LINE add constraint FK_ACCUMED_CLAIM_LINE_CLAIM_ID foreign key (CLAIM_ID) references ACCUMED_CLAIM(ID);
create index IDX_ACCUMED_CLAIM_LINE_CLAIM on ACCUMED_CLAIM_LINE (CLAIM_ID);
