alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_PATIENT_ID foreign key (PATIENT_ID) references ACCUMED_PATIENT(ID);
alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_REFERRED_BY_ID foreign key (REFERRED_BY_ID) references ACCUMED_PROVIDER(ID);
alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_DOCTOR_ID foreign key (DOCTOR_ID) references ACCUMED_PROVIDER(ID);
alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_FACILITY_ID foreign key (FACILITY_ID) references ACCUMED_FACILITY(ID);
create index IDX_ACCUMED_CLAIM_REFERRED_BY on ACCUMED_CLAIM (REFERRED_BY_ID);
create index IDX_ACCUMED_CLAIM_FACILITY on ACCUMED_CLAIM (FACILITY_ID);
create index IDX_ACCUMED_CLAIM_DOCTOR on ACCUMED_CLAIM (DOCTOR_ID);
create index IDX_ACCUMED_CLAIM_PATIENT on ACCUMED_CLAIM (PATIENT_ID);
