alter table ACCUMED_PATIENT add constraint FK_ACCUMED_PATIENT_FAM_DOC_ID foreign key (FAM_DOC_ID) references ACCUMED_PROVIDER(ID);
create index IDX_ACCUMED_PATIENT_FAM_DOC on ACCUMED_PATIENT (FAM_DOC_ID);
