alter table ACCUMED_PATIENT add constraint FK_ACCUMED_PATIENT_FACILITY_ID foreign key (FACILITY_ID) references ACCUMED_FACILITY(ID);
create index IDX_ACCUMED_PATIENT_FACILITY on ACCUMED_PATIENT (FACILITY_ID);
