alter table ACCUMED_CLAIM add constraint FK_ACCUMED_CLAIM_PROVIDER_ID foreign key (PROVIDER_ID) references ACCUMED_PROVIDER(ID);
create index IDX_ACCUMED_CLAIM_PROVIDER on ACCUMED_CLAIM (PROVIDER_ID);
