alter table ACCUMED_PATIENT add constraint FK_ACCUMED_PATIENT_FAMILY_DOCTOR_ID foreign key (FAMILY_DOCTOR_ID) references ACCUMED_PROVIDER(ID);
create index IDX_ACCUMED_PATIENT_FAMILY_DOCTOR on ACCUMED_PATIENT (FAMILY_DOCTOR_ID);
