create table ACCUMED_QUICK_SERVICE_CODE_BILLABLE_SERVICE_CODE_LINK (
    QUICK_SERVICE_CODE_ID uuid,
    BILLABLE_SERVICE_CODE_ID uuid,
    primary key (QUICK_SERVICE_CODE_ID, BILLABLE_SERVICE_CODE_ID)
);
